# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql42
#   labels:
#     app: mysql42
# spec:
#   type: NodePort
#   ports:
#   - port: 3306
#     targetPort: 3306
#     nodePort: 3306
#     protocol: TCP
#     name: mysql42
#   selector:
#     app: mysql42

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql42
#   labels:
#     app: mysql42
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql42
#   labels:
#     app: mysql42
# spec:
#   selector:
#     matchLabels:
#       app: mysql42
#   template:
#     metadata:
#       labels:
#         app: mysql42
#     spec:
#       containers:
#       - name: mysql42
#         image: mysql42
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 3306
#           name: mysql42
#         volumeMounts:
#         - name: mysql42
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql42
#         persistentVolumeClaim:
#           claimName: mysql42

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql42
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          imagePullPolicy: IfNotPresent  
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-volume