apiVersion: v1
kind: Service
metadata:
    name: wordpress42
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
    selector:
      app: wordpress42
     
---

apiVersion: apps/v1
kind: Service
metadata:
    name: wordpress42
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
    selector:
      app: wordpress42