apiVersion: v1
kind: Service
metadata:
    name: wordpress42
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
    selector:
      app: wordpress-app
     
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress42
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress42
        image: wordpress42
        ports:
        - containerPort: 5050
        imagePullPolicy: Never